###########
# BUILDER #
###########

# base image
FROM node:10.13 as builder

RUN mkdir -p /usr/src/frontend
RUN mkdir -p /usr/src/backend

# set working directory
WORKDIR /usr/src/frontend

# install frontend dependencies
COPY ["./frontend/package.json", "./frontend/package-lock.json*", "./"]
RUN npm install --production --silent

# create build
COPY ./frontend/ /usr/src/frontend
COPY ./backend/schema.graphql /usr/src/backend
RUN npm run build



#########
# FINAL #
#########

# base image
FROM nginx:1.15.9

# copy static files
COPY --from=builder /usr/src/frontend/build /usr/share/nginx/html

# expose port
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
