# Generated by Django 2.1.4 on 2019-03-09 11:14

import datetime
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[(events.models.EventCategory('Рестораны и Кафе'), 'Рестораны и Кафе'), (events.models.EventCategory('Развлечения'), 'Развлечения'), (events.models.EventCategory('Концерты'), 'Концерты'), (events.models.EventCategory('Красота'), 'Красота'), (events.models.EventCategory('Разное'), 'Разное')], default=events.models.EventCategory('Разное'), max_length=25),
        ),
        migrations.AddField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='share',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
