# Generated by Django 2.1.7 on 2019-03-09 23:09

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190309_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[(events.models.EventCategory('Рестораны и Кафе'), 'Рестораны и Кафе'), (events.models.EventCategory('Развлечения'), 'Развлечения'), (events.models.EventCategory('Концерты'), 'Концерты'), (events.models.EventCategory('Красота'), 'Красота'), (events.models.EventCategory('Разное'), 'Разное')], default=events.models.EventCategory('Разное'), max_length=25),
        ),
    ]
